### ISSUE TITLE
`Unsupported class file major version 65` In 1.20.5 with 7.0.97

### ISSUE THREAD

**Issue by Coloryr** [neoforged/NeoGradle#148]
```
下午1:41:07: 正在执行 'build'…

> Task :cacheLauncherMetadata UP-TO-DATE
> Task :cacheVersionManifest1.20.5 UP-TO-DATE
> Task :cacheVersionExecutableClient1.20.5 UP-TO-DATE
> Task :cacheVersionExecutableServer1.20.5 UP-TO-DATE
> Task :cacheVersionMappingsClient1.20.5 UP-TO-DATE
> Task :cacheVersionMappingsServer1.20.5 UP-TO-DATE
> Task :neoFormForgesAccessTransformerProvider_script_neoforge.cfg UP-TO-DATE
> Task :neoFormForgesAccessTransformerProvideraccesstransformer.cfg UP-TO-DATE
> Task :neoFormListLibraries
> Task :neoFormStripClient UP-TO-DATE
> Task :neoFormExtractServer UP-TO-DATE
> Task :neoFormStripServer UP-TO-DATE
> Task :neoFormMerge UP-TO-DATE
> Task :neoFormMergeMappings UP-TO-DATE
> Task :neoFormRename

> Task :neoFormApplyForgesAccessTransformer FAILED
16 actionable tasks: 3 executed, 13 up-to-date
[13:41:11] [main/INFO]: Access Transformer processor running version 8.0.7+8.0.7+master.43473d43
[13:41:11] [main/INFO]: Command line arguments [--inJar, E:\code\AllMusic_Server\neoforge_1_20_5\build\neoForm\neoFormJoined1.20.5-20240423.152201\steps\rename\output.jar, --outJar, E:\code\AllMusic_Server\neoforge_1_20_5\build\neoForm\neoFormJoined1.20.5-20240423.152201\steps\applyForgesAccessTransformer\output.jar, --atFile, E:\code\AllMusic_Server\neoforge_1_20_5\build\neoForm\neoFormJoined1.20.5-20240423.152201\accesstransformers\Forges\accesstransformer.cfg, --atFile, E:\code\AllMusic_Server\neoforge_1_20_5\build\neoForm\neoFormJoined1.20.5-20240423.152201\accesstransformers\Forges\_script_neoforge.cfg]
[13:41:11] [main/INFO]: Reading from E:\code\AllMusic_Server\neoforge_1_20_5\build\neoForm\neoFormJoined1.20.5-20240423.152201\steps\rename\output.jar
[13:41:11] [main/INFO]: Writing to E:\code\AllMusic_Server\neoforge_1_20_5\build\neoForm\neoFormJoined1.20.5-20240423.152201\steps\applyForgesAccessTransformer\output.jar
[13:41:11] [main/INFO]: Transformer file E:\code\AllMusic_Server\neoforge_1_20_5\build\neoForm\neoFormJoined1.20.5-20240423.152201\accesstransformers\Forges\accesstransformer.cfg
[13:41:11] [main/INFO]: Transformer file E:\code\AllMusic_Server\neoforge_1_20_5\build\neoForm\neoFormJoined1.20.5-20240423.152201\accesstransformers\Forges\_script_neoforge.cfg
[13:41:11] [main/WARN]: Found existing output jar E:\code\AllMusic_Server\neoforge_1_20_5\build\neoForm\neoFormJoined1.20.5-20240423.152201\steps\applyForgesAccessTransformer\output.jar, overwriting
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 65
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:284)
	at net.minecraftforge.accesstransformer.TransformerProcessor.lambda$processJar$3(TransformerProcessor.java:108)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1939)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at net.minecraftforge.accesstransformer.TransformerProcessor.processJar(TransformerProcessor.java:104)
	at net.minecraftforge.accesstransformer.TransformerProcessor.main(TransformerProcessor.java:81)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':neoFormApplyForgesAccessTransformer'.
> Process 'command 'C:\Program Files\Java\jdk21\bin\java.exe'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 4s
下午1:41:11: 执行完成 'build'。

```

**Comment by Shadows-of-Fire** [comment]
Mojang bumped the java version to Java 21 for 1.20.5.  You will need to update to that.

**Comment by Coloryr** [comment]
> Mojang bumped the java version to Java 21 for 1.20.5. You will need to update to that.

yes, it already 21

**Comment by Technici4n** [comment]
You also need to upgrade gradle to 8.6 or 8.7.

**Comment by Coloryr** [comment]
> You also need to upgrade gradle to 8.6 or 8.7.

is 8.6 now

```
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.6-bin.zip
networkTimeout=10000
validateDistributionUrl=true
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
```

**Comment by Coloryr** [comment]
I have switched back to 1.20.4 and can compile normally, but it cannot be loaded by the 1.20.5 server

![image](https://github.com/neoforged/NeoGradle/assets/26276037/05af9c18-aca8-450c-a170-dc024684fdfe)

**Comment by Technici4n** [comment]
You'll need NG 7.0.104 at least. And of course 1.20.4 mods won't work in 1.20.5. If you need more support please ask on discord it will be more efficient.

**Comment by Coloryr** [comment]
ok

**Comment by Coloryr** [comment]
NG 7.0.104 is work now
