### ISSUE TITLE
Issues using multi mod setup with eclipse

### ISSUE THREAD

**Issue by CreativeMD** [neoforged/NeoGradle#162]
Hey there,
I'm having some difficulties setting up my multi-mod workspace in 1.20.6. For some reason the neoforge jar dependency is added twice for each project causing a couple of issues inside eclipse but also when running the game giving the following error:

```
Exception in thread "main" net.neoforged.fml.ModLoadingException: Loading errors encountered: [
	fml.modloading.multiple_copies_on_classpath
]
	at MC-BOOTSTRAP/fml_loader@3.0.19/net.neoforged.fml.util.DevEnvUtils.findFileSystemRootOfFileOnClasspath(DevEnvUtils.java:78)
	at MC-BOOTSTRAP/fml_loader@3.0.19/net.neoforged.fml.loading.targets.CommonUserdevLaunchHandler.collectAdditionalModFileLocators(CommonUserdevLaunchHandler.java:24)
	at MC-BOOTSTRAP/fml_loader@3.0.19/net.neoforged.fml.loading.FMLLoader.beginModScan(FMLLoader.java:131)
	at MC-BOOTSTRAP/fml_loader@3.0.19/net.neoforged.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:76)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:95)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$7(TransformationServicesHandler.java:94)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1787)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:96)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:50)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.Launcher.run(Launcher.java:84)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.2/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@2.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:176)
	at cpw.mods.bootstraplauncher@2.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:65)
```

When viewing the projects 'Build Path', this dependency can be found twice:
![image](https://github.com/neoforged/NeoGradle/assets/1353495/0e345921-cf13-434d-87ac-9f31aad21875)

My setup can be found here: https://github.com/CreativeMD/ForgeMods/tree/1.20.5

**Comment by Technici4n** [comment]
This FML rework exposed a flaw in how NeoGradle handles multiple projects in general. The current workaround for this issue is to make sure that the `ng_dummy_ng` dependency does not leak outside of your Gradle project.

Instead of adding it to `implementation`, you should be able to add it to both `compileOnly` and `localRuntime`:
```gradle
// Sets up a dependency configuration called 'localRuntime'.
// This configuration should be used instead of 'runtimeOnly' to declare
// a dependency that will be present for runtime testing but that is
// "optional", meaning it will not be pulled by dependents of this mod.
configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    compileOnly "net.neoforged.neoforge:neoforge:XXX"
    localRuntime "net.neoforged.neoforge:neoforge:XXX"
}
```
I haven't tested this but there is a good chance that it will solve the issue.

**Comment by CreativeMD** [comment]
That fixed it! Thank you so much! Should I leave this issue open till this is properly fixed or should I close it?

**Comment by shartte** [comment]
> That fixed it! Thank you so much! Should I leave this issue open till this is properly fixed or should I close it?

Please leave it open for now, we're looking into the details behind this problem.
