### ISSUE TITLE
NeoGradle does not seem to work in some cases with Linux

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoGradle#31]
ie:
```
loic@loic-System-Product-Name:~/Neo/NeoForge$ JAVA_HOME='/lib/jvm/java-17-openjdk-amd64'  ./gradlew setup

> Configure project :
NeoForge version 20.2.35-beta

> Task :neoforge:neoFormApplyUserAccessTransformer
[16:23:51] [main/INFO]: Access Transformer processor running version 8.0.7+8.0.7+master.43473d43
[16:23:51] [main/INFO]: Command line arguments [--inJar, /home/loic/Neo/NeoForge/projects/neoforge/build/neoForm/neoFormJoined1.20.2-20231019.002635/steps/rename/output.jar, --outJar, /home/loic/Neo/NeoForge/projects/neoforge/build/neoForm/neoFormJoined1.20.2-20231019.002635/steps/applyUserAccessTransformer/output.jar, --atFile, /home/loic/Neo/NeoForge/projects/neoforge/build/neoForm/neoFormJoined1.20.2-20231019.002635/accesstransformers/User/accesstransformer.cfg]
[16:23:51] [main/INFO]: Reading from /home/loic/Neo/NeoForge/projects/neoforge/build/neoForm/neoFormJoined1.20.2-20231019.002635/steps/rename/output.jar
[16:23:51] [main/INFO]: Writing to /home/loic/Neo/NeoForge/projects/neoforge/build/neoForm/neoFormJoined1.20.2-20231019.002635/steps/applyUserAccessTransformer/output.jar
[16:23:51] [main/INFO]: Transformer file /home/loic/Neo/NeoForge/projects/neoforge/build/neoForm/neoFormJoined1.20.2-20231019.002635/accesstransformers/User/accesstransformer.cfg
[16:23:51] [main/WARN]: Found existing output jar /home/loic/Neo/NeoForge/projects/neoforge/build/neoForm/neoFormJoined1.20.2-20231019.002635/steps/applyUserAccessTransformer/output.jar, overwriting
[16:23:53] [main/INFO]: JAR transformation complete /home/loic/Neo/NeoForge/projects/neoforge/build/neoForm/neoFormJoined1.20.2-20231019.002635/steps/applyUserAccessTransformer/output.jar

BUILD SUCCESSFUL in 1m 46s
44 actionable tasks: 40 executed, 4 from cache
loic@loic-System-Product-Name:~/Neo/NeoForge$ JAVA_HOME='/lib/jvm/java-17-openjdk-amd64'  ./gradlew :neoforge:runClient

> Configure project :
NeoForge version 20.2.35-beta

> Task :neoforge:runClient FAILED
[16:24:44.374] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher running: args [--gameDir, "/home/loic/Neo/NeoForge/projects/neoforge/run/client", --fml.neoForgeVersion, 20.2.35-beta, --fml.fmlVersion, 1.0.9, --fml.mcVersion, 1.20.2, --fml.neoFormVersion, 20231019.002635, --username, Dev, --version, neoforge, --accessToken, ❄❄❄❄❄❄❄❄, --userrun, mojang, --versionrun, release, --launchTarget, forgeclientdev, --assetsDir, /home/loic/.gradle/caches/minecraft/assets/1.20.2, --assetIndex, asset-index] 
[16:24:44.378] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.8.1 by Private Build; OS Linux arch amd64 version 6.5.9-2-liquorix-amd64 
Exception in thread "main" joptsimple.OptionArgumentConversionException: Cannot parse argument '"/home/loic/Neo/NeoForge/projects/neoforge/run/client"' of option gameDir
        at MC-BOOTSTRAP/jopt.simple@5.0.4/joptsimple.AbstractOptionSpec.convertWith(AbstractOptionSpec.java:92)
        at MC-BOOTSTRAP/jopt.simple@5.0.4/joptsimple.ArgumentAcceptingOptionSpec.convert(ArgumentAcceptingOptionSpec.java:277)
        at MC-BOOTSTRAP/jopt.simple@5.0.4/joptsimple.OptionSet.valuesOf(OptionSet.java:223)
        at MC-BOOTSTRAP/jopt.simple@5.0.4/joptsimple.OptionSet.valueOf(OptionSet.java:172)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ArgumentHandler.setArgs(ArgumentHandler.java:50)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:86)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
Caused by: joptsimple.ValueConversionException: Directory ["/home/loic/Neo/NeoForge/projects/neoforge/run/client"] does not exist
        at MC-BOOTSTRAP/jopt.simple@5.0.4/joptsimple.util.PathConverter.convert(PathConverter.java:28)
        at MC-BOOTSTRAP/jopt.simple@5.0.4/joptsimple.util.PathConverter.convert(PathConverter.java:14)
        at MC-BOOTSTRAP/jopt.simple@5.0.4/joptsimple.internal.Reflection.convertWith(Reflection.java:124)
        at MC-BOOTSTRAP/jopt.simple@5.0.4/joptsimple.AbstractOptionSpec.convertWith(AbstractOptionSpec.java:90)
        ... 9 more

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':neoforge:runClient'.
> Process 'command '/usr/lib/jvm/java-17-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
5 actionable tasks: 1 executed, 4 up-to-date
loic@loic-System-Product-Name:~/Neo/NeoForge$ 

```
It doesn't seem to work, it crashes every time.

**Comment by Lolothepro** [comment]
fixed by https://github.com/neoforged/NeoForge/pull/354
