### ISSUE TITLE
NeoGradle error checking with access transformers rather unclear.

### ISSUE THREAD

**Issue by KiriCattus** [neoforged/NeoGradle#43]
While setting up the stock NeoForge MDK and enabling access transformers (This line)
``minecraft.accessTransformers.file rootProject.file('src/main/resources/META-INF/accesstransformer.cfg')``
If you forget to create the file, name it wrong or in my case pull the file from an older setup using Forge, NeoGradle doesn't *clearly* tell you it can't find the access transformer file it's looking for and instead provides this error.
```
21:56:11: Executing 'idePostSync'...

> Task :cacheLauncherMetadata UP-TO-DATE
> Task :cacheVersionManifest1.20.2 UP-TO-DATE
> Task :cacheVersionExecutableClient1.20.2 UP-TO-DATE
> Task :cacheVersionExecutableServer1.20.2 UP-TO-DATE
> Task :cacheVersionMappingsClient1.20.2 UP-TO-DATE
> Task :cacheVersionMappingsServer1.20.2 UP-TO-DATE
> Task :neoFormForgesAccessTransformerProvider_script_neoforge.cfg UP-TO-DATE
> Task :neoFormForgesAccessTransformerProvideraccesstransformer.cfg UP-TO-DATE
> Task :neoFormListLibraries UP-TO-DATE
> Task :neoFormStripClient UP-TO-DATE
> Task :neoFormExtractServer UP-TO-DATE
> Task :neoFormStripServer UP-TO-DATE
> Task :neoFormMerge UP-TO-DATE
> Task :neoFormMergeMappings UP-TO-DATE
> Task :neoFormRename UP-TO-DATE
> Task :neoFormApplyForgesAccessTransformer UP-TO-DATE

> Task :neoFormApplyUserAccessTransformer

> Task :neoFormDecompile FAILED
18 actionable tasks: 2 executed, 16 up-to-date
[21:56:15] [main/ERROR]: Option Parsing Error
joptsimple.MissingRequiredOptionsException: Missing required option(s) [atFile/atfile]
	at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426) ~[accesstransformers-8.0.7-fatjar.jar:?]
	at joptsimple.OptionParser.parse(OptionParser.java:400) ~[accesstransformers-8.0.7-fatjar.jar:?]
	at net.minecraftforge.accesstransformer.TransformerProcessor.main(TransformerProcessor.java:39) [accesstransformers-8.0.7-fatjar.jar:8.0.7+8.0.7+master.43473d43]

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':neoFormDecompile' (type 'Execute').
  - In plugin 'net.neoforged.gradle.common.CommonProjectPlugin' type 'net.neoforged.gradle.common.runtime.tasks.Execute' property 'arguments.files.$0.file' specifies file 'F:\projects\modding\third-party-mods\MDK\build\neoForm\neoFormJoined1.20.2-20231019.002635\steps\applyUserAccessTransformer\output.jar' which doesn't exist.
    
    Reason: An input file was expected to be present but it doesn't exist.
    
    Possible solutions:
      1. Make sure the file exists before the task is called.
      2. Make sure that the task which produces the file is declared as an input.
    
    Please refer to https://docs.gradle.org/8.1.1/userguide/validation_problems.html#input_file_does_not_exist for more details about this problem.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
21:56:15: Execution finished 'idePostSync'.
```

(In short, error message should be made clearer as to what the issue is as it was rather unclear)

**Comment by GamingHP** [comment]
now _how_ do i fix it?

**Comment by KiriCattus** [comment]
It's been like 3 years, I forgot this issue was even open, I suspect my AT file was named incorrectly but I couldn't tell you to be honest
